title: Heather Bannister
title_separator: "|"
email: hbannister.author@gmail.com
description: Author. Book Enthusiast. <br><i>"A meet-cute between Suspense and New-Adult Romance."</i>
show_downloads: false
google_analytics: false
theme: jekyll-theme-leap-day
search: true
markdown: kramdown
timezone: America/New_York

# include:
#   - _pages

# plugins:
#   - jekyll-paginate
#   - jekyll-sitemap
#   - jekyll-gist
#   - jekyll-feed
#   - jemoji
#   - jekyll-include-cache

author:
  name   : "Heather Bannister"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "she/her"
  links:
    - label: "instagram"
      icon: "fas fa-fw fa-instagram"
      url: "https://instagram.com/hbannister.author"

footer:
  links:
    - label: "instagram"
      icon: "fas fa-fw fa-instagram"
      url: "https://instagram.com/hbannister.author"

# defaults:
#   # _posts
#   - scope:
#       path: ""
#       type: posts
#     values:
#       layout: single
#       author_profile: true
#       read_time: true
#       comments: true
#       share: true
#       related: true
#   # _pages
#   - scope:
#       path: "_pages"
#       type: pages
#     values:
#       layout: single
#       author_profile: true
